name: Deploy to Tomcat

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '11'
      - run: mvn package
      - run: scp target/*.war ubuntu@34.201.242.12:/var/lib/tomcat8/webapps
      - run: ssh ubuntu@34.201.242.12 "cd /var/lib/tomcat8/webapps && manager-script deploy *.war"
